[package]
name = "pokemon-battle-client"
version = "0.3.2"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
firecore-battle-net = { path=".." }
firecore-game = { git="https://github.com/DoNotDoughnut/pokemon-game", default-features=false, features=["static-link", "logger"] }
firecore-battle-client = { git="https://github.com/DoNotDoughnut/pokemon-game", package = "firecore-battle-client", default-features=false, features=["static-link"] }

[build-dependencies]
font-builder = { git="https://github.com/DoNotDoughnut/pokemon-game", package="font-builder" }
dex-builder = { git="https://github.com/DoNotDoughnut/pokemon-game", package="dex-builder" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
