[package]
name = "pokemon-battle-client"
version = "0.3.3"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]
default = ["audio"]
audio = ["firecore-battle-gui/audio"]

[dependencies]
firecore-battle-net = { path=".." }
firecore-dependencies = { git="https://github.com/DoNotDoughnut/firecore-dependencies" }
firecore-battle-gui = { git="https://github.com/DoNotDoughnut/firecore-battle-gui", default-features = false }
log = "0.4"
simple_logger = "1"

[build-dependencies]
firecore-font-builder = { git="https://github.com/DoNotDoughnut/firecore-font-builder" }
firecore-pokedex-builder = { git="https://github.com/DoNotDoughnut/firecore-pokedex-builder" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
