[package]
name = "pokemon-battle-client"
version = "0.1.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firecore-battle-net = { path = ".." }
firecore-game = { git = "https://github.com/DoNotDoughnut/firecore-game", default-features = false, features = ["battle", "ser", "static-link"] }

[build-dependencies]
winres = "0.1"