[package]
name = "firecore-battle-net"
version = "0.3.3"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
repository = "https://github.com/DoNotDoughnut/pokemon-battle-net"
# default-run = "pokemon-battle-server"

[features]
default = []
server = ["firecore-battle/host"]

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
firecore-battle = { git="https://github.com/DoNotDoughnut/firecore-battle", default-features = false }
bincode = "1.3"
serde = { version="1.0", features=["derive"] }
message-io = { version="0.14", features=["tcp"], default-features=false }
parking_lot = "0.11"
rand = "0.8"
uuid = { version="0.8", features=["serde", "v4"] }

[workspace]
members = ["client", "server", "server/dex-builder-mini"]
