[package]
name = "firecore-battle-net"
version = "0.1.0"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
# default-run = "pokemon-battle-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
firecore-pokedex = { git = "https://github.com/DoNotDoughnut/firecore-game", package = "firecore-pokedex" }
serde = { version = "1.0", features = ["derive"] }
laminar = "0.5"
simple_logger = "*"

[workspace]
members = [
    "client",
    "server",
    "server/dex-builder-mini"
]