[package]
name = "pokemon-battle-server"
version = "0.1.0"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firecore-battle-net = {path = ".."}
crossbeam-channel = "0.5"
dashmap = "4.0"